name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Check script permissions
      run: |
        chmod +x setup.sh
        
    - name: Validate script
      run: |
        # Test if script can create a test project
        ./setup.sh <<< "test-project"
        
    - name: Verify generated structure
      run: |
        cd test-project
        # Check if essential files exist
        test -f package.json
        test -f tsconfig.json
        test -d src
        test -d tests 